### PR TITLE
[DONOTMERGE] [R] [Q-MR0] Remove COPY_HEADERS, use exported includes, add CleanSpec.mk

### PR DESCRIPTION
**Pull request by ix5**
**DO NOT MERGE:** Grab-bag PR to get msm8996 and below up on R at all. Will need a new branch to stay compatible with Q and below.

### CODE REVIEW

**Comment by MarijnS95** [comment]
@ix5 Unless I made a mistake this seems fine on Q, where `LOCAL_EXPORT_C_INCLUDE_DIRS` is available. It compiles properly, too.

**Comment by ix5** [comment]
Did you clear `$(TARGET_OUT_HEADERS)`?

**Comment by MarijnS95** [comment]
@ix5 I obviously forgot that initially, but these headers seem to be self-contained in the repo. `libloc_loader.h` and `ds_client.h` aren't used anywhere else in hardware nor vendor.

That said this built a vendor image successfully for discovery after deleting `obj/include`, too. Would you mind trying as well to be extra careful, given my mistakes?

**Comment by ix5** [comment]
Added a `CleanSpec.mk` file to clean headers.

**Comment by ix5** [comment]
Now that thanks to my, ahem, _herculean efforts_, 4.9 devices will be able to use the 8.1 OSS location and GPS HAL, this PR makes little sense.

Will pick the needed parts and then apply them on top of 8.1.

**Pull request closed without merging**
